import Head from 'next/head'
import Image from 'next/image'
import './i18n';

import {Banner} from '../components/banner/Banner.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>EliB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/EliB.svg" />
      </Head>
      <Banner />
      
    </>
  )
}
