import React from 'react'

import Head from 'next/head'
import Image from 'next/image'
// import './i18n';

import {Banner} from '../components/banner/Banner.js'
import {About} from '../components/about/About.js'


export default function Home() {
  return (
    <>
      <Head>
        <title>EliB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/EliB.svg" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      
      <Banner />
      <About />
      
    </>
  )
}
