import Head from 'next/head'
import Image from 'next/image'
import './i18n';

import {Banner} from '../components/banner/Banner.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>EliB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Banner />
      

      <footer>
        <a
          href="https://w3layouts.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Design by{' '}
          <span>W3layouts</span>
        </a>
      </footer>
    </div>
  )
}
